# docker-compose.yml - Wazuh Security Monitoring Stack
# This file defines the complete Wazuh stack with proper health checks and persistence

version: '3.8'

services:
  wazuh-manager:
    image: wazuh/wazuh-manager:${WAZUH_VERSION:-4.7.0}
    container_name: wazuh-manager
    hostname: wazuh-manager
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "1514:1514"      # Wazuh agent communication
      - "1515:1515"      # Wazuh agent enrollment
      - "514:514/udp"    # Syslog
      - "55000:55000"    # Wazuh API
    environment:
      - INDEXER_URL=https://wazuh-indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=MyS3cr37P450r.*-
    volumes:
      # Persistent data volumes
      - wazuh_api_configuration:/var/ossec/api/configuration
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue
      - wazuh_var_multigroups:/var/ossec/var/multigroups
      - wazuh_integrations:/var/ossec/integrations
      - wazuh_active_response:/var/ossec/active-response/bin
      - wazuh_agentless:/var/ossec/agentless
      - wazuh_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat
      # SSL certificates
      - ./config/wazuh_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem:ro
      - ./config/wazuh_indexer_ssl_certs/wazuh-manager.pem:/etc/ssl/filebeat.pem:ro
      - ./config/wazuh_indexer_ssl_certs/wazuh-manager-key.pem:/etc/ssl/filebeat.key:ro
      # Configuration files
      - ./config/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:55000/agents/000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      wazuh-indexer:
        condition: service_healthy
    networks:
      - wazuh
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  wazuh-indexer:
    image: wazuh/wazuh-indexer:${WAZUH_VERSION:-4.7.0}
    container_name: wazuh-indexer
    hostname: wazuh-indexer
    restart: unless-stopped
    ports:
      - "9200:9200"      # Elasticsearch API
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"  # Adjusted for t3.xlarge
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "network.host=0.0.0.0"
      - "plugins.security.ssl.transport.pemcert_filepath=certs/wazuh-indexer.pem"
      - "plugins.security.ssl.transport.pemkey_filepath=certs/wazuh-indexer-key.pem"
      - "plugins.security.ssl.transport.pemtrustedcas_filepath=certs/root-ca.pem"
      - "plugins.security.ssl.http.enabled=true"
      - "plugins.security.ssl.http.pemcert_filepath=certs/wazuh-indexer.pem"
      - "plugins.security.ssl.http.pemkey_filepath=certs/wazuh-indexer-key.pem"
      - "plugins.security.ssl.http.pemtrustedcas_filepath=certs/root-ca.pem"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      # Persistent data
      - wazuh_indexer_data:/var/lib/wazuh-indexer
      # SSL certificates
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem:ro
      - ./config/wazuh_indexer_ssl_certs/wazuh-indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh-indexer-key.pem:ro
      - ./config/wazuh_indexer_ssl_certs/wazuh-indexer.pem:/usr/share/wazuh-indexer/certs/wazuh-indexer.pem:ro
      - ./config/wazuh_indexer_ssl_certs/admin.pem:/usr/share/wazuh-indexer/certs/admin.pem:ro
      - ./config/wazuh_indexer_ssl_certs/admin-key.pem:/usr/share/wazuh-indexer/certs/admin-key.pem:ro
      # Configuration files
      - ./config/wazuh_indexer/wazuh.indexer.yml:/usr/share/wazuh-indexer/opensearch.yml:ro
      - ./config/wazuh_indexer/internal_users.yml:/usr/share/wazuh-indexer/opensearch-security/internal_users.yml:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -k -u admin:SecretPassword https://localhost:9200/_cluster/health | grep -q '\"status\":\"green\\|yellow\"' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - wazuh
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:${WAZUH_VERSION:-4.7.0}
    container_name: wazuh-dashboard
    hostname: wazuh-dashboard
    restart: unless-stopped
    ports:
      - "443:5601"       # HTTPS Dashboard access
      - "80:5601"        # HTTP Dashboard access (redirects to HTTPS)
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - WAZUH_API_URL=https://wazuh-manager
      - DASHBOARD_USERNAME=kibanaserver
      - DASHBOARD_PASSWORD=kibanaserver
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=MyS3cr37P450r.*-
      - OPENSEARCH_HOSTS=["https://wazuh-indexer:9200"]
    volumes:
      # SSL certificates
      - ./config/wazuh_indexer_ssl_certs/wazuh-dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem:ro
      - ./config/wazuh_indexer_ssl_certs/wazuh-dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem:ro
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem:ro
      # Configuration files
      - ./config/wazuh_dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml:ro
      - ./config/wazuh_dashboard/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -k -I https://localhost:5601/app/wazuh | grep -q 'HTTP/1.1 200\\|HTTP/1.1 302' || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 180s
    depends_on:
      wazuh-indexer:
        condition: service_healthy
      wazuh-manager:
        condition: service_healthy
    networks:
      - wazuh
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Wazuh agent for self-monitoring
  wazuh-agent:
    image: wazuh/wazuh-agent:${WAZUH_VERSION:-4.7.0}
    container_name: wazuh-agent
    hostname: wazuh-agent-docker
    restart: unless-stopped
    environment:
      - WAZUH_MANAGER=wazuh-manager
      - WAZUH_AGENT_GROUP=docker
      - WAZUH_AGENT_NAME=wazuh-agent-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/host/var/log:ro
      - /etc/hostname:/etc/hostname:ro
      - /etc/hosts:/etc/hosts:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    depends_on:
      wazuh-manager:
        condition: service_healthy
    networks:
      - wazuh
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  wazuh_api_configuration:
    driver: local
    driver_opts:
      type: none
      device: /opt/wazuh/data/api_configuration
      o: bind
  wazuh_etc:
    driver: local
    driver_opts:
      type: none
      device: /opt/wazuh/data/etc
      o: bind
  wazuh_logs:
    driver: local
    driver_opts:
      type: none
      device: /opt/wazuh/logs
      o: bind
  wazuh_queue:
    driver: local
    driver_opts:
      type: none
      device: /opt/wazuh/data/queue
      o: bind
  wazuh_var_multigroups:
    driver: local
    driver_opts:
      type: none
      device: /opt/wazuh/data/var_multigroups
      o: bind
  wazuh_integrations:
    driver: local
    driver_opts:
      type: none
      device: /opt/wazuh/data/integrations
      o: bind
  wazuh_active_response:
    driver: local
    driver_opts:
      type: none
      device: /opt/wazuh/data/active_response
      o: bind
  wazuh_agentless:
    driver: local
    driver_opts:
      type: none
      device: /opt/wazuh/data/agentless
      o: bind
  wazuh_wodles:
    driver: local
    driver_opts:
      type: none
      device: /opt/wazuh/data/wodles
      o: bind
  filebeat_etc:
    driver: local
    driver_opts:
      type: none
      device: /opt/wazuh/data/filebeat_etc
      o: bind
  filebeat_var:
    driver: local
    driver_opts:
      type: none
      device: /opt/wazuh/data/filebeat_var
      o: bind
  wazuh_indexer_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/wazuh/data/indexer
      o: bind

networks:
  wazuh:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16